"use client"

import { useEffect, useState, useMemo } from "react"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { useUIStore } from "@/stores/uiStore"
import { useOrgStore } from "@/stores/orgStore"
import { ArrowLeftRight } from "lucide-react"

export function BridgeFormDialog() {
  const { isBridgeDialogOpen, editingBridgeId, closeBridgeDialog } = useUIStore()
  const { nodes, bridges, addBridge, updateBridge } = useOrgStore()

  const [name, setName] = useState("")
  const [scope, setScope] = useState("")
  const [companyTargetId, setCompanyTargetId] = useState("")
  const [hospitalTargetId, setHospitalTargetId] = useState("")
  const [useCustomName, setUseCustomName] = useState(false)

  // 메모이제이션된 노드 필터링
  const companyNodes = useMemo(
    () => nodes.filter((n) => n.org === "company"),
    [nodes]
  )
  const hospitalNodes = useMemo(
    () => nodes.filter((n) => n.org === "hospital"),
    [nodes]
  )

  const bridge = editingBridgeId
    ? bridges.find((b) => b.id === editingBridgeId)
    : null

  // 선택된 노드 정보
  const selectedCompanyNode = useMemo(
    () => companyNodes.find((n) => n.id === companyTargetId),
    [companyNodes, companyTargetId]
  )
  const selectedHospitalNode = useMemo(
    () => hospitalNodes.find((n) => n.id === hospitalTargetId),
    [hospitalNodes, hospitalTargetId]
  )

  // 자동 생성 이름
  const autoGeneratedName = useMemo(() => {
    if (selectedCompanyNode && selectedHospitalNode) {
      return `${selectedCompanyNode.name} ↔ ${selectedHospitalNode.name}`
    }
    return ""
  }, [selectedCompanyNode, selectedHospitalNode])

  // 다이얼로그 열림/닫힘 시에만 초기화
  useEffect(() => {
    if (!isBridgeDialogOpen) return

    if (editingBridgeId) {
      const editBridge = bridges.find((b) => b.id === editingBridgeId)
      if (editBridge) {
        setName(editBridge.name)
        setScope(editBridge.scope || "")
        setCompanyTargetId(editBridge.companyTargetId)
        setHospitalTargetId(editBridge.hospitalTargetId)

        const companyNode = nodes.find((n) => n.id === editBridge.companyTargetId)
        const hospitalNode = nodes.find((n) => n.id === editBridge.hospitalTargetId)
        const expectedAutoName = companyNode && hospitalNode
          ? `${companyNode.name} ↔ ${hospitalNode.name}`
          : ""
        setUseCustomName(editBridge.name !== expectedAutoName)
      }
    } else {
      setName("")
      setScope("")
      setCompanyTargetId("")
      setHospitalTargetId("")
      setUseCustomName(false)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isBridgeDialogOpen, editingBridgeId])

  // 자동 이름 사용 시 이름 업데이트
  useEffect(() => {
    if (!useCustomName && autoGeneratedName) {
      setName(autoGeneratedName)
    }
  }, [autoGeneratedName, useCustomName])

  const handleSave = async () => {
    const finalName = useCustomName ? name.trim() : autoGeneratedName
    if (!finalName || !companyTargetId || !hospitalTargetId) return

    if (editingBridgeId) {
      await updateBridge(editingBridgeId, {
        name: finalName,
        scope: scope.trim() || undefined,
        companyTargetId,
        hospitalTargetId,
      })
    } else {
      await addBridge(finalName, companyTargetId, hospitalTargetId)
      if (scope.trim()) {
        const newBridge = bridges[bridges.length - 1]
        if (newBridge) {
          await updateBridge(newBridge.id, { scope: scope.trim() })
        }
      }
    }

    closeBridgeDialog()
  }

  const handleClose = () => {
    closeBridgeDialog()
  }

  const isValid = (useCustomName ? name.trim() : autoGeneratedName) && companyTargetId && hospitalTargetId

  return (
    <Dialog open={isBridgeDialogOpen} onOpenChange={(open) => !open && handleClose()}>
      <DialogContent onClose={handleClose}>
        <DialogHeader>
          <DialogTitle>
            {editingBridgeId ? "가교 편집" : "가교 추가"}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          <div className="grid grid-cols-[1fr_auto_1fr] gap-2 items-end">
            <div className="space-y-2">
              <Label htmlFor="companyTarget">Company 대상 *</Label>
              <select
                id="companyTarget"
                value={companyTargetId}
                onChange={(e) => setCompanyTargetId(e.target.value)}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              >
                <option value="">선택하세요</option>
                {companyNodes.map((node) => (
                  <option key={node.id} value={node.id}>
                    {node.name} {node.title && `(${node.title})`}
                  </option>
                ))}
              </select>
            </div>

            <div className="pb-2">
              <ArrowLeftRight className="h-5 w-5 text-muted-foreground" />
            </div>

            <div className="space-y-2">
              <Label htmlFor="clientTarget">Client 대상 *</Label>
              <select
                id="clientTarget"
                value={hospitalTargetId}
                onChange={(e) => setHospitalTargetId(e.target.value)}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              >
                <option value="">선택하세요</option>
                {hospitalNodes.map((node) => (
                  <option key={node.id} value={node.id}>
                    {node.name} {node.title && `(${node.title})`}
                  </option>
                ))}
              </select>
            </div>
          </div>

          {selectedCompanyNode && selectedHospitalNode && (
            <div className="bg-muted/50 rounded-lg p-3 text-sm">
              <div className="flex items-center justify-between gap-4">
                <div className="flex-1 text-center">
                  <p className="font-medium">{selectedCompanyNode.name}</p>
                  {selectedCompanyNode.title && (
                    <p className="text-xs text-muted-foreground">{selectedCompanyNode.title}</p>
                  )}
                </div>
                <ArrowLeftRight className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                <div className="flex-1 text-center">
                  <p className="font-medium">{selectedHospitalNode.name}</p>
                  {selectedHospitalNode.title && (
                    <p className="text-xs text-muted-foreground">{selectedHospitalNode.title}</p>
                  )}
                </div>
              </div>
            </div>
          )}

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="bridgeName">가교 이름</Label>
              <label className="flex items-center gap-2 text-xs text-muted-foreground cursor-pointer">
                <input
                  type="checkbox"
                  checked={useCustomName}
                  onChange={(e) => {
                    setUseCustomName(e.target.checked)
                    if (!e.target.checked) {
                      setName(autoGeneratedName)
                    }
                  }}
                  className="h-3 w-3"
                />
                직접 입력
              </label>
            </div>
            <Input
              id="bridgeName"
              value={useCustomName ? name : autoGeneratedName}
              onChange={(e) => setName(e.target.value)}
              placeholder={autoGeneratedName || "양측 대상을 선택하면 자동 생성됩니다"}
              disabled={!useCustomName}
              className={!useCustomName ? "bg-muted" : ""}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="bridgeScope">업무 범위</Label>
            <Textarea
              id="bridgeScope"
              value={scope}
              onChange={(e) => setScope(e.target.value)}
              placeholder="이 가교를 통해 협업하는 업무 범위를 입력하세요"
              rows={3}
            />
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={handleClose}>
            취소
          </Button>
          <Button onClick={handleSave} disabled={!isValid}>
            {editingBridgeId ? "저장" : "추가"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
